version: "3.9"

services:
  nginx:
    container_name: nginx-app
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
  web:
    container_name: my-flask
    image: python:3.7
    working_dir: "$APP_HOME"
    command: bash -c "pip install gunicorn flask && gunicorn -b 0.0.0.0:8000 app:app"
    # Use volumes to create storage containers.
    volumes:
      - ./app.py:/app/app.py
      - /home/jxbromley/my_volume:/storage
    #   - app_data:/app
    # Place your environment variables here (i.e. DATABASE_HOST=db)
    # environment:
    #  - DATABASE_HOST=db
#Place your persistant volumes here
#volumes:
#   app_data:
